# Use an official Node.js runtime as the base image
FROM node:18

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json into the container
COPY package*.json ./

# Copy the frontend code into the container
COPY ./frontend ./

# Install application dependencies
RUN npm install

# Start the application
CMD ["npx", "live-server"]