version: '1'
services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - 5501:8080
    depends_on:
      - backend
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:5000
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/travel_destinations_ola
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data: